########################################################
# Copyright 2019-2020 program was created VMware, Inc. #
# SPDX-License-Identifier: Apache-2.0                  #
########################################################

version: '3'

networks:
  fate-network:

volumes:
  fate_flow_logs:
  shared_dir_examples:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /path/to/host/dir/examples
  shared_dir_federatedml:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /path/to/host/dir/federatedml

services:
  rollsite:
    image: "${PREFIX}/eggroll:${TAG}"
    ports:
      - "9370:9370"
    environment:
      PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: python
    volumes:
      - ./confs/proxy/conf:/data/projects/fate/proxy/conf
    networks:
      - fate-network

  fateboard:
    image: "${PREFIX}/fateboard:${TAG}"
    ports:
      - "8080:8080"
    volumes:
      - ./confs/fateboard/conf:/data/projects/fate/fateboard/conf
      - fate_flow_logs:/data/projects/fate/python/logs
    networks:
      - fate-network
    depends_on:
      - meta-service
      - python

  clustermanager:
    image: "${PREFIX}/roll:${TAG}"
    expose:
      - 8011
    volumes:
      - ./confs/roll/conf:/data/projects/fate/roll/conf
    environment:
      PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: python
    networks:
      - fate-network
    depends_on:
      - meta-service

  nodemanager:
    image: "${PREFIX}/egg:${TAG}"
    expose:
      - 7888
      - 7778
      - "50000-60000"
    environment:
      PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: cpp 
      LD_LIBRARY_PATH: $$LD_LIBRARY_PATH:/usr/local/lib:/data/projects/fate/eggroll/storage-service-cxx/third_party/lib
      PYTHONPATH: /data/projects/fate/eggroll/python
      GLOG_log_dir: /data/projects/fate/eggroll/storage-service-cxx/logs
    volumes:
        - ./confs/egg/conf:/data/projects/fate/eggroll/egg/conf
        - ./confs/federatedml/conf/server_conf.json:/data/projects/fate/eggroll/python/eggroll/conf/server_conf.json
        - ./confs/egg/data-dir:/data/projects/fate/data-dir
    networks:
      - fate-network

  python:
    image: "${PREFIX}/python:${TAG}"
    ports:
      - "9360:9360"
      - "9380:9380"
    restart: always
    volumes:
      - shared_dir_federatedml:/data/projects/fate/python/federatedml
      - shared_dir_examples:/data/projects/fate/python/examples
      - ./confs/federatedml/conf:/data/projects/fate/python/arch/conf
      - ./confs/federatedml/conf:/data/projects/fate/python/eggroll/conf
      - ./confs/fate_flow/conf/settings.py:/data/projects/fate/python/fate_flow/settings.py
      - ./confs/fate_flow/conf/server_conf.json:/data/projects/fate/python/arch/conf/server_conf.json
      - fate_flow_logs:/data/projects/fate/python/logs
    depends_on:
      - redis
      - meta-service
      - proxy
      - roll
      - egg
      - mysql
    networks:
      - fate-network

  mysql:
    image: "mysql:8"
    expose:
      - 3306
    volumes:
      - ./confs/mysql/init:/docker-entrypoint-initdb.d/
      - ./confs/mysql/data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: fate_dev
      MYSQL_DATABASE: fate
      MYSQL_USER: fate
      MYSQL_PASSWORD: fate_dev
    networks:
      - fate-network
